movieproject/movieapp/urls.py
from . import views
from django.urls import path,include
app_name='movieapp'

urlpatterns = [

    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.

class movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movies
class MovieForm(forms.ModelForm):
    class Meta:
        model = movies
        fields = ['name','desc','year','image']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from .forms import MovieForm
from . models import movies


def index(request):
    movie=movies.objects.all()
    context={'movie_list':movie}
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=movies.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=movies(name=name,desc=desc,year=year,image=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie = movies.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request, id):
    if request.method =='POST':
        movie = movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name"><br>
    <input type="text" name="desc" placeholder="Enter the movie description"><br>
    <input type="text" name="year" placeholder="Enter the movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit" style="background-color:green;">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  <h2>Are you want to delete this movie?</h2>
  <input type="submit" style="background-color:red;color:white;">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movie.image.url}}" width="700" height="600">
        </div>
<div class="col-md-6">
    <h1>{{movie.name}}</h1>
    <h3>{{movie.desc}}</h3>
    <h4>{{movie.year}}</h4>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>

</div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" style="background-color:red;color:white;">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top"  src="{{i.image.url}}"  alt="Card image cap" width="350px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text" style="color:black;">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Movie details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
<a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
{% endblock %}